locals {
  env           = "dev"
  region        = "us-east-1"
  zone1         = "us-east-1a"
  zone2         = "us-east-1b"
  eks_name      = "cluster1"
  eks_version   = "1.29"
  profile       = "eks-admin"
  cidr_block    = "10.0.0.0/16"
  key_pair_name = "ec2-aws-key"
  instance_type = "t2.micro"
  server_name   = "Web Server"
  my_ip         = "${chomp(data.http.my_ip.response_body)}/32"
  vpc_name      = "Bilarn Vpc"
  aws_profile   = "eks-admin"
}
